In [ ]:
import os
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import root_mean_squared_error, r2_score

In [2]:
path = '../data/raw/'
df = pd.read_csv(os.path.join(path, 'housing.csv'))
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [3]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [4]:
df['total_bedrooms'].mean()

np.float64(537.8705525375618)

## Splitting Data

In [5]:
X = df.drop("median_house_value", axis=1)
y = df["median_house_value"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

## Handling Missing Values

In [6]:
X.head(3)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   

   population  households  median_income ocean_proximity  
0       322.0       126.0         8.3252        NEAR BAY  
1      2401.0      1138.0         8.3014        NEAR BAY  
2       496.0       177.0         7.2574        NEAR BAY

In [7]:
X.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
ocean_proximity         0
dtype: int64

In [8]:
imputer = SimpleImputer(strategy="median")

X_train["total_bedrooms"] = imputer.fit_transform(
    X_train[["total_bedrooms"]]
)

X_test["total_bedrooms"] = imputer.transform(
    X_test[["total_bedrooms"]]
)

In [9]:
X_train['total_bedrooms'].isnull().sum(), X_test['total_bedrooms'].isnull().sum(),

(np.int64(0), np.int64(0))

---

## Doing Standardization

In [10]:
numeric_features = [
    'longitude',
    'latitude',
    'housing_median_age',
    'total_rooms',
    'total_bedrooms',
    'population',
    'households',
    'median_income'
]

In [11]:
scalar = StandardScaler()

X_train[numeric_features] = scalar.fit_transform(X_train[numeric_features])
X_test[numeric_features] = scalar.transform(X_test[numeric_features])

In [12]:
X_train.head(3)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
14196   1.272587 -1.372811            0.348490     0.222569        0.211228   
8267    0.709162 -0.876696            1.618118     0.340293        0.593094   
17445  -0.447603 -0.460146           -1.952710    -0.342597       -0.495226   

       population  households  median_income ocean_proximity  
14196    0.768276    0.322906      -0.326196      NEAR OCEAN  
8267    -0.098901    0.672027      -0.035843      NEAR OCEAN  
17445   -0.449818   -0.430461       0.144701      NEAR OCEAN

---

## Encoding for Categorical Data

In [13]:
print("Original ocean_proximity unique values:")
print(X_train["ocean_proximity"].value_counts())

Original ocean_proximity unique values:
ocean_proximity
<1H OCEAN     7341
INLAND        5227
NEAR OCEAN    2086
NEAR BAY      1854
ISLAND           4
Name: count, dtype: int64


In [14]:
# Create encoder
encoder = OneHotEncoder(
    sparse_output=False,      # Get dense array (not sparse matrix)
    handle_unknown='ignore'   # Ignore new categories in test
)

# Fit on train, transform train
encoded_train = encoder.fit_transform(X_train[["ocean_proximity"]])

# Transform test (uses train categories only)
encoded_test = encoder.transform(X_test[["ocean_proximity"]])

# Get proper column names
encoded_cols = encoder.get_feature_names_out()

print("Encoded column names:", encoded_cols)
print("Train shape:", encoded_train.shape)  # (16512, 5)
print("Test shape:", encoded_test.shape)    # (4128, 5)


Encoded column names: ['ocean_proximity_<1H OCEAN' 'ocean_proximity_INLAND'
 'ocean_proximity_ISLAND' 'ocean_proximity_NEAR BAY'
 'ocean_proximity_NEAR OCEAN']
Train shape: (16512, 5)
Test shape: (4128, 5)


In [15]:
# Convert to DataFrames with correct indices
encoded_train_df = pd.DataFrame(
    encoded_train, columns=encoded_cols, index=X_train.index
)
encoded_test_df = pd.DataFrame(
    encoded_test, columns=encoded_cols, index=X_test.index
)

print("\nFirst few rows:")
encoded_train_df.head()


First few rows:


ocean_proximity_<1H OCEAN  ocean_proximity_INLAND  \
14196                        0.0                     0.0   
8267                         0.0                     0.0   
17445                        0.0                     0.0   
14265                        0.0                     0.0   
2271                         0.0                     1.0   

       ocean_proximity_ISLAND  ocean_proximity_NEAR BAY  \
14196                     0.0                       0.0   
8267                      0.0                       0.0   
17445                     0.0                       0.0   
14265                     0.0                       0.0   
2271                      0.0                       0.0   

       ocean_proximity_NEAR OCEAN  
14196                         1.0  
8267                          1.0  
17445                         1.0  
14265                         1.0  
2271                          0.0

In [16]:
# Drop original ocean_proximity and add encoded columns
X_train = X_train.drop("ocean_proximity", axis=1).join(encoded_train_df)
X_test = X_test.drop("ocean_proximity", axis=1).join(encoded_test_df)

print("Final shapes:")
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)

print(encoded_train)

Final shapes:
X_train: (16512, 13)
X_test: (4128, 13)
[[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 ...
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [17]:
X_train.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
14196   1.272587 -1.372811            0.348490     0.222569        0.211228   
8267    0.709162 -0.876696            1.618118     0.340293        0.593094   
17445  -0.447603 -0.460146           -1.952710    -0.342597       -0.495226   
14265   1.232698 -1.382172            0.586545    -0.561490       -0.409306   
2271   -0.108551  0.532084            1.142008    -0.119565       -0.256559   

       population  households  median_income  ocean_proximity_<1H OCEAN  \
14196    0.768276    0.322906      -0.326196                        0.0   
8267    -0.098901    0.672027      -0.035843                        0.0   
17445   -0.449818   -0.430461       0.144701                        0.0   
14265   -0.007434   -0.380587      -1.017864                        0.0   
2271    -0.485877   -0.314962      -0.171488                        0.0   

       ocean_proximity_INLAND  ocean_proximity_ISLAND  \
14196                     0.0                     0.0   
8267                      0.0                     0.0   
17445                     0.0                     0.0   
14265                     0.0                     0.0   
2271                      1.0                     0.0   

       ocean_proximity_NEAR BAY  ocean_proximity_NEAR OCEAN  
14196                       0.0                         1.0  
8267                        0.0                         1.0  
17445                       0.0                         1.0  
14265                       0.0                         1.0  
2271                        0.0                         0.0

---

## Model Training and Evaluation

In [18]:
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

LinearRegression()

In [19]:
from sklearn.metrics import root_mean_squared_error

y_train_pred = lin_reg.predict(X_train)
y_test_pred  = lin_reg.predict(X_test)

train_rmse = root_mean_squared_error(y_train, y_train_pred)
test_rmse  = root_mean_squared_error(y_test,  y_test_pred)

print("Train RMSE:", train_rmse)
print("Test RMSE :", test_rmse)

Train RMSE: 68433.93736666226
Test RMSE : 70059.19333925014


### Calculate target variance explained by your model

In [20]:
train_r2 = lin_reg.score(X_train, y_train)
test_r2 = lin_reg.score(X_test, y_test)

print("Train R²:", train_r2)
print("Test R²:", test_r2)

Train R²: 0.6496648627123223
Test R²: 0.6254382675296266


---

## Save Model and Metrics

In [21]:
import joblib

# Save model
joblib.dump(lin_reg, "../artifacts/linear/linear_model.joblib")

['../artifacts/linear/linear_model.joblib']

In [22]:
import json
from pathlib import Path

metrics_path = Path("../artifacts/linear/metrics.json")

metrics = {}

# Load existing OR create new
if metrics_path.exists():
    with open(metrics_path, "r") as f:
        metrics = json.load(f)
    print(f"Loaded existing metrics from {metrics_path}")
else:
    metrics = {}
    print(f"Created new metrics file at {metrics_path}")

# Ensure base structure
metrics.setdefault("model_family", "linear_models")
metrics.setdefault("models", {})

# Add Linear Regression metrics
metrics["models"]["linear_regression"] = {
    "train": {
        "rmse": train_rmse,
        "r2": train_r2
    },
    "test": {
        "rmse": test_rmse,
        "r2": test_r2
    }
}

# Save back
with open(metrics_path, "w") as f:
    json.dump(metrics, f, indent=4)

Loaded existing metrics from ../artifacts/linear/metrics.json


---

## Trying Regularization

In [23]:
from sklearn.linear_model import Ridge
from sklearn.metrics import root_mean_squared_error

ridge_reg = Ridge(alpha=1.0)
ridge_reg.fit(X_train, y_train)

Ridge()

In [24]:
y_train_pred_ridge = ridge_reg.predict(X_train)
y_test_pred_ridge  = ridge_reg.predict(X_test)

train_rmse_ridge = root_mean_squared_error(y_train, y_train_pred_ridge)
test_rmse_ridge  = root_mean_squared_error(y_test, y_test_pred_ridge)

print("Ridge Train RMSE:", train_rmse_ridge)
print("Ridge Test RMSE :", test_rmse_ridge)

Ridge Train RMSE: 68434.99589612993
Ridge Test RMSE : 70066.02112093243


In [25]:
train_r2_ridge = ridge_reg.score(X_train, y_train)
test_r2_ridge = ridge_reg.score(X_test, y_test)

print("Ridge Train R²:", train_r2_ridge)
print("Ridge Test R²:", test_r2_ridge)

Ridge Train R²: 0.6496540247290437
Ridge Test R²: 0.625365256401925


In [26]:
import json
from pathlib import Path

metrics_path = Path("../artifacts/linear/metrics.json")

# Load existing OR create new
if metrics_path.exists():
    with open(metrics_path, "r") as f:
        metrics = json.load(f)
    print(f"Loaded existing metrics from {metrics_path}")
else:
    metrics = {}
    print(f"Created new metrics file at {metrics_path}")

# Ensure ridge container exists
metrics["models"].setdefault("ridge_regression", {})

# Add Ridge metrics for alpha = 1.0
metrics["models"]["ridge_regression"]["alpha_1.0"] = {
    "train": {
        "rmse": train_rmse_ridge,
        "r2": train_r2_ridge
    },
    "test": {
        "rmse": test_rmse_ridge,
        "r2": test_r2_ridge
    }
}

# Save back
with open(metrics_path, "w") as f:
    json.dump(metrics, f, indent=4)

Loaded existing metrics from ../artifacts/linear/metrics.json


---